resources:
- manager.yaml
- priority_classes.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/defilantech/llmkube-controller
  newTag: 0.4.0
