{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llmkube.fullname" . }}-controller-manager-metrics-service
  namespace: {{ include "llmkube.namespace" . }}
  labels:
    {{- include "llmkube.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
  - name: https
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: https
  selector:
    {{- include "llmkube.selectorLabels" . | nindent 4 }}
{{- end }}
