{{- if and .Values.rbac.create .Values.controllerManager.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "llmkube.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "llmkube.namespace" . }}
  labels:
    {{- include "llmkube.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "llmkube.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "llmkube.serviceAccountName" . }}
  namespace: {{ include "llmkube.namespace" . }}
{{- end }}
