apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter-external
  namespace: gpu-operator-resources
  labels:
    app: nvidia-dcgm-exporter
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 9400
    targetPort: 9400
    nodePort: 30940
    protocol: TCP
  selector:
    app: nvidia-dcgm-exporter
